##
# Naemon
#
# Started with the base playbook, modified for centos based on http://www.naemon.org/documentation/usersguide/quickstart-centos.html
# 2015-12 Modified from the original by Pol Llovet <pol.llovet@gmail.com>
#

---
- name: check the admin pass status
  debug: 
    msg: "Admin pass: {{thruk_admin_password}}"

- name: add epel repo
  tags:
    - naemon
    - naemon_only
  yum:
    name: http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm

- name: install naemon and dependancies
  tags:
    - naemon
    - naemon_only
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - dejavu-fonts-common 
    - perl 
    - xorg-x11-server-Xvfb 
    - wget 
    - gd 
    - libXpm 
    - httpd
    - http://labs.consol.de/naemon/release/v1.0.3/rhel6/x86_64/naemon-core-dbg-1.0.3-1.rhel6.x86_64.rpm
    - http://labs.consol.de/naemon/release/v1.0.3/rhel6/x86_64/naemon-core-1.0.3-1.rhel6.x86_64.rpm
    - http://labs.consol.de/naemon/release/v1.0.3/rhel6/x86_64/naemon-devel-1.0.3-1.rhel6.x86_64.rpm
    - http://labs.consol.de/naemon/release/v1.0.3/rhel6/x86_64/naemon-livestatus-1.0.3-1.rhel6.x86_64.rpm
    - http://labs.consol.de/naemon/release/v1.0.3/rhel6/x86_64/naemon-1.0.3-1.rhel6.x86_64.rpm
    - http://labs.consol.de/naemon/release/v1.0.3/rhel6/x86_64/libnaemon-1.0.3-1.rhel6.x86_64.rpm
    - http://labs.consol.de/naemon/release/v1.0.3/rhel6/x86_64/naemon-tools-1.0.3-1.rhel6.x86_64.rpm

- name: disable selinux
  tags:
    - naemon
    - naemon_only
  selinux: state=disabled

- name: permanently disable selinux
  tags:
    - naemon
    - naemon_only  
  lineinfile: 
    dest: /etc/selinux/config 
    regexp: ^SELINUX= 
    line: SELINUX=disabled

- name: change naemon plugins directory
  tags:
    - naemon
    - naemon_only
  lineinfile: 
    dest: /etc/naemon/resource.cfg 
    regexp: '^\$USER1\$=/usr/lib/naemon/plugins$' 
    line: '$USER1$=/usr/lib64/nagios/plugins' 
    backrefs: yes
  notify: restart naemon

- name: set naemon configuration
  tags:
    - naemon
    - naemon_only
  template: 
    src: naemon.cfg.j2 
    dest: /etc/naemon/naemon.cfg 
    owner: naemon 
    group: naemon 
    mode: 0644
  notify: restart naemon

- name: install Nagios plugins
  tags:
    - naemon
    - naemon_only
  yum: 
    name: "{{item}}" 
    state: present
  with_items:
    - nagios-plugins 
    - nagios-plugins-all 
    - nagios-plugins-nrpe 
    - nrpe

- name: start the services and enable them
  tags:
    - naemon
    - naemon_only
  service: 
    name: "{{item}}"
    state: started
    enabled: yes
  with_items:
    - httpd
    - naemon

- name: open 80 and 443 in iptables for web traffic
  tags:
    - naemon
    - thruk
    - pnp4nagios
    - naemon_only
  iptables: chain=INPUT jump=ACCEPT protocol=tcp destination_port={{item}} comment="Allow {{item}} web traffic"
  with_items:
    - 80
    - 443

# Thruk
- include: thruk.yml
  tags:
    - naemon
    - thruk
  when: install_thruk is defined and install_thruk

# PNPNagios
- include: pnp4nagios.yml
  tags:
    - naemon
    - pnp4nagios
  when: install_pnp4nagios is defined and install_pnp4nagios
