##
# 2015-12 Modified from the original by Pol Llovet <pol.llovet@gmail.com>
#
---
- name: install thruk and dependancies
  yum: name={{ item }} update_cache=yes state=present
  with_items:
    - python-passlib
    - http://labs.consol.de/naemon/release/v1.0.3/rhel6/x86_64/naemon-thruk-libs-1.0.3-1.rhel6.x86_64.rpm
    - http://labs.consol.de/naemon/release/v1.0.3/rhel6/x86_64/naemon-thruk-reporting-1.0.3-1.rhel6.x86_64.rpm
    - http://labs.consol.de/naemon/release/v1.0.3/rhel6/x86_64/naemon-thruk-1.0.3-1.rhel6.x86_64.rpm

- name: set thruk admin password
  tags:
    - naemon
    - thruk
  htpasswd: path=/etc/naemon/htpasswd name=admin password={{thruk_admin_password}}
  when:
    - thruk_admin_password is defined and thruk_admin_password
